<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Content\UnAddeContent\**" />
    <EmbeddedResource Remove="Content\UnAddeContent\**" />
    <None Remove="Content\UnAddeContent\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Content\ActIcons\MoveActIcon.png" />
    <None Remove="Content\ColorReplace.fx" />
    <None Remove="Content\GrassTiles\GrassTile.png" />
    <None Remove="Content\MonsterAnimations\AirOoze\AirOozeIdle.png" />
    <None Remove="Content\MonsterAnimations\AirOoze\AirOozeWalk.png" />
    <None Remove="Content\MonsterAnimations\EarthOoze\EarthOozeGraspingRoot.png" />
    <None Remove="Content\MonsterAnimations\EarthOoze\EarthOozeGraspingRootVE.png" />
    <None Remove="Content\MonsterAnimations\EarthOoze\EarthOozeIdle.png" />
    <None Remove="Content\MonsterAnimations\EarthOoze\EarthOozeWalkDown.png" />
    <None Remove="Content\MonsterAnimations\EarthOoze\EarthOozeWalkUp.png" />
    <None Remove="Content\MonsterAnimations\FireOoze\FireOozeIdle.png" />
    <None Remove="Content\MonsterAnimations\FireOoze\FireOozeLavaBallVE.png" />
    <None Remove="Content\MonsterAnimations\FireOoze\FireOozeWalkDown.png" />
    <None Remove="Content\MonsterAnimations\FireOoze\FireOozeWalkUp.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeIcicleStabDown.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeIcicleStabUp.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeIdle.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamDown.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamUp.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeWalk.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeWalkDown.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeWalkUp.png" />
    <None Remove="Content\MonsterIcons\AngryPlantIcon.png" />
    <None Remove="Content\MonsterIcons\EarthOoze.png" />
    <None Remove="Content\MonsterIcons\TrainingDummyIcon.png" />
    <None Remove="Content\NPC\Eyes\LeftCircular.png" />
    <None Remove="Content\NPC\Eyes\LeftFlat.png" />
    <None Remove="Content\NPC\Eyes\LeftInward.png" />
    <None Remove="Content\NPC\Eyes\LeftOutward.png" />
    <None Remove="Content\NPC\Eyes\LeftTriangle.png" />
    <None Remove="Content\NPC\Eyes\RightCircular.png" />
    <None Remove="Content\NPC\Eyes\RightFlat.png" />
    <None Remove="Content\NPC\Eyes\RightInward.png" />
    <None Remove="Content\NPC\Eyes\RightOutward.png" />
    <None Remove="Content\NPC\Eyes\RightTriangle.png" />
    <None Remove="Content\NPC\Head\Normalhead.png" />
    <None Remove="Content\NPC\Head\ShortWideHead.png" />
    <None Remove="Content\NPC\Head\SmallHead.png" />
    <None Remove="Content\NPC\Head\TallSkinnyHead.png" />
    <None Remove="Content\NPC\Head\THead.png" />
    <None Remove="Content\ParticleDefault.png" />
    <None Remove="Content\PlayerSprites\PlayerBody.png" />
    <None Remove="Content\PlayerSprites\PlayerBodyColored.png" />
    <None Remove="Content\PlayerSprites\PlayerHead.png" />
    <None Remove="Content\PlayerSprites\PlayerNeck.png" />
    <None Remove="Content\PlayerSprites\PlayerSprites.png" />
    <None Remove="Content\PlayerSprites\PlayerSS.png" />
    <None Remove="Content\Shaders\Smoke.fx" />
    <None Remove="Content\Songs\newGameIntroCinBackground.mp3" />
    <None Remove="Content\TileCell\3arrows.png" />
    <None Remove="Content\TileCell\arrow.png" />
    <None Remove="Content\Tiles\-1_0_0.png" />
    <None Remove="Content\Tiles\-1_0_0OLD %282%29.png" />
    <None Remove="Content\Tiles\-1_0_0OLD.png" />
    <None Remove="Content\Tiles\-1_0_0\ForeDarkFog_-1_0_0.png" />
    <None Remove="Content\Tiles\-1_0_0\GlowMound.png" />
    <None Remove="Content\Tiles\-1_0_0\Vines1.png" />
    <None Remove="Content\Tiles\0_-1_0OLD.png" />
    <None Remove="Content\Tiles\0_-1_0\0_-1_0.png" />
    <None Remove="Content\Tiles\0_-1_0\ForeDarkFog_0_-1_0.png" />
    <None Remove="Content\Tiles\0_-1_0\GlowMound3_0_-1_0.png" />
    <None Remove="Content\Tiles\0_0_0.png" />
    <None Remove="Content\Tiles\0_0_0old.png" />
    <None Remove="Content\Tiles\0_0_0\0_0_0.png" />
    <None Remove="Content\Tiles\0_0_0\ForeDarkFog_0_0_0.png" />
    <None Remove="Content\Tiles\Level1\0_0_1\0_0_1.png" />
    <None Remove="Content\Tiles\Level1\0_0_1\BGCloud_0_0_1.png" />
    <None Remove="Content\Tiles\Level1\0_0_1\BGSmoke_0_0_1.png" />
    <None Remove="Content\Tiles\1_4_0.png" />
    <None Remove="Content\Tiles\BackgroundSmoke.png" />
    <None Remove="Content\Tiles\Level1\1_-1_1\1_-1_1.png" />
    <None Remove="Content\Tiles\Level1\1_0_1\1_0_1.png" />
    <None Remove="Content\WhiteSmoke.png" />
    <None Remove="Data\CombatMonsterData\AnimationData.json" />
    <None Remove="Data\MapTile\MapTile_-1_-1_0.json" />
    <None Remove="Data\MapTile\MapTile_0_-1_0.json" />
    <None Remove="Data\MapTile\MapTile_0_0_0.json" />
    <None Remove="Data\SaveData\SaveJson\savegame1.json" />
    <None Remove="Data\SaveData\SaveJson\savegame2.json" />
    <None Remove="Data\SaveData\SaveJson\savegame3.json" />
    <None Remove="Data\VE\veData.json" />
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\ActIcons\MoveActIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\AirOoze\AirOozeIdle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\AirOoze\AirOozeWalk.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\EarthOoze\EarthOozeGraspingRoot.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\EarthOoze\EarthOozeGraspingRootVE.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\EarthOoze\EarthOozeIdle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\EarthOoze\EarthOozeWalkDown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\EarthOoze\EarthOozeWalkUp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FireOoze\FireOozeLavaBall.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FireOoze\FireOozeIdle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FireOoze\FireOozeLavaBallVE.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FireOoze\FireOozeWalkDown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FireOoze\FireOozeWalkUp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeIcicleStabDown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeIcicleStabUp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeWalkDown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeWalkUp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\EarthOoze.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\LeftCircular.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\LeftFlat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\LeftInward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\LeftOutward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\LeftTriangle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\RightCircular.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\RightFlat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\RightInward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\RightOutward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Eyes\RightTriangle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Head\NormalHead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Head\ShortWideHead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Head\SmallHead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Head\TallSkinnyHead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\NPC\Head\THead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ParticleDefault.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerBody.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerBodyColored.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerHead.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerNeck.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Shaders\ColorReplace.fx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\GrassTiles\GrassTile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeIdle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamDown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamUp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeWalk.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\AngryPlantIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\OozeIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\TrainingDummyIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerSprites.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerSS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Shaders\Smoke.fx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Songs\newGameIntroCinBackground.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TileCell\3arrows.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TileCell\arrow.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_-1_0\-1_-1_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\-1_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0OLD (2).png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0OLD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MiscAssets\GlowMound.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\ForeDarkFog_-1_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\LowerRocks_-1_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\Vines1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_-1_0OLD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_-1_0\0_-1_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_-1_0\ForeDarkFog_0_-1_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_-1_0\GlowMound3_0_-1_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0old.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0\0_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0\ForeDarkFog_0_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0\LowerRocks_0_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\0_0_1\0_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\0_0_1\BGCloud_0_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\0_0_1\BGSmoke_0_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\1_4_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\BackgroundSmoke.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\1_-1_1\1_-1_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\1_0_1\1_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\1_0_1\BGCloud_1_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\Level1\1_0_1\BGSmoke_1_0_1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\WhiteSmoke.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\CombatMonsterData\AnimationData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level1\MapTile_1_-1_1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level1\MapTile_1_0_1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level0\MapTile_-1_-1_0.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level0\MapTile_0_-1_0.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level0\MapTile_-1_0_0.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level0\MapTile_0_0_0.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\Level1\MapTile_0_0_1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\SaveData\SaveJson\savegame1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\VE\veData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="AnimationFolder\SmokeText\" />
    <Folder Include="Content\UnAdded\" />
    <Folder Include="Content\UI\" />
    <Folder Include="Data\SaveData\SaveStates\" />
    <Folder Include="Entities\Monster\SummonedMonsters\" />
    <Folder Include="Managers\CombatMan\CombatBehaviors\" />
    <Folder Include="World\MapTiles\CombatTileCell\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\Aspects\AspectData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\CombatMonsterData\CombatMonsterData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Dialogue\DialogueData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\NPCs\NPCData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\PlayMonsterJson\PlayMonsters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Quests\QuestData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Resistances\Resistance.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\SaveData\SaveJson\savegameTemplate.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Settings\SettingData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Triggers\TriggerData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>