<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Content\UnAddeContent\**" />
    <EmbeddedResource Remove="Content\UnAddeContent\**" />
    <None Remove="Content\UnAddeContent\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Content\ColorReplace.fx" />
    <None Remove="Content\GrassTiles\GrassTile.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeIdle.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamBottomLeft.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamBottomRight.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamTopLeft.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeSlamTopRight.png" />
    <None Remove="Content\MonsterAnimations\FrostOoze\FrostOozeWalk.png" />
    <None Remove="Content\MonsterIcons\AngryPlantIcon.png" />
    <None Remove="Content\MonsterIcons\OozeIcon.png" />
    <None Remove="Content\MonsterIcons\TrainingDummyIcon.png" />
    <None Remove="Content\PlayerSprites\PlayerSprites.png" />
    <None Remove="Content\PlayerSprites\PlayerSS.png" />
    <None Remove="Content\Songs\newGameIntroCinBackground.mp3" />
    <None Remove="Content\TileCell\3arrows.png" />
    <None Remove="Content\TileCell\arrow.png" />
    <None Remove="Content\Tiles\-1_0_0.png" />
    <None Remove="Content\Tiles\-1_0_0OLD %282%29.png" />
    <None Remove="Content\Tiles\-1_0_0OLD.png" />
    <None Remove="Content\Tiles\-1_0_0\GlowMound.png" />
    <None Remove="Content\Tiles\-1_0_0\Vines1.png" />
    <None Remove="Content\Tiles\0_-1_0OLD.png" />
    <None Remove="Content\Tiles\0_0_0.png" />
    <None Remove="Content\Tiles\0_0_0old.png" />
    <None Remove="Content\Tiles\1_4_0.png" />
    <None Remove="Data\SaveData\SaveJson\savegame1.json" />
    <None Remove="Data\SaveData\SaveJson\savegame2.json" />
    <None Remove="Data\SaveData\SaveJson\savegame3.json" />
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
    <None Remove="Data\TileJson\MapTile_-1_0_0.json" />
    <None Remove="Data\TileJson\MapTile_1_4_0.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\Shaders\ColorReplace.fx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\GrassTiles\GrassTile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeIdle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamBottomLeft.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamBottomRight.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamTopLeft.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeSlamTopRight.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterAnimations\FrostOoze\FrostOozeWalk.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\AngryPlantIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\OozeIcon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MonsterIcons\TrainingDummyIcon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerSprites.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\PlayerSprites\PlayerSS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Songs\newGameIntroCinBackground.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TileCell\3arrows.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\TileCell\arrow.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\-1_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0OLD (2).png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0OLD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\MiscAssets\GlowMound.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\-1_0_0\Vines1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_-1_0OLD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\0_0_0old.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Tiles\1_4_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\SaveData\SaveJson\savegame1.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\SaveData\SaveJson\savegame2.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\SaveData\SaveJson\savegame3.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\MapTile_-1_0_0.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\MapTile_0_0_0.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\MapTile\MapTile_1_4_0.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Content\UnAdded\" />
    <Folder Include="Content\UI\" />
    <Folder Include="Data\SaveData\SaveStates\" />
    <Folder Include="Data\TileJson\" />
    <Folder Include="Entities\Monster\SummonedMonsters\" />
    <Folder Include="Managers\CombatMan\CombatBehaviors\" />
    <Folder Include="World\MapTiles\CombatTileCell\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\Aspects\AspectData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Attacks\AttackData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\CombatMonsterData\CombatMonsterData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Dialogue\DialogueData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\NPCs\NPCData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\PlayMonsterJson\PlayMonsters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Quests\QuestData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Resistances\Resistance.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\SaveData\SaveJson\savegameTemplate.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Settings\SettingData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Triggers\TriggerData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>